export const cropCalendarData = [
  {
    id: 1,
    name: "Wheat",
    emoji: "🌾",
    plantingMonth: "November",
    harvestMonth: "April",
    waterNeeds: "Moderate",
    bestSoil: "Loamy",
    season: "Winter",
    color: "from-amber-400 to-yellow-500",
  },
  {
    id: 2,
    name: "Rice",
    emoji: "🌿",
    plantingMonth: "June",
    harvestMonth: "October",
    waterNeeds: "High",
    bestSoil: "Clay",
    season: "Summer",
    color: "from-green-400 to-emerald-500",
  },
  {
    id: 3,
    name: "Cotton",
    emoji: "🌸",
    plantingMonth: "March",
    harvestMonth: "October",
    waterNeeds: "Moderate",
    bestSoil: "Sandy",
    season: "Spring",
    color: "from-pink-300 to-rose-400",
  },
  {
    id: 4,
    name: "Sugarcane",
    emoji: "🎋",
    plantingMonth: "February",
    harvestMonth: "December",
    waterNeeds: "Very High",
    bestSoil: "Loamy",
    season: "Spring",
    color: "from-lime-400 to-green-500",
  },
  {
    id: 5,
    name: "Corn",
    emoji: "🌽",
    plantingMonth: "April",
    harvestMonth: "August",
    waterNeeds: "Moderate",
    bestSoil: "Loamy",
    season: "Summer",
    color: "from-yellow-300 to-orange-400",
  },
  {
    id: 6,
    name: "Tomatoes",
    emoji: "🍅",
    plantingMonth: "January",
    harvestMonth: "April",
    waterNeeds: "Moderate",
    bestSoil: "Sandy",
    season: "Winter",
    color: "from-red-400 to-rose-500",
  },
];

const STORE = "https://48cdqc-i6.myshopify.com";

export const products = [
  {
    id: 1,
    name: "Premium Wheat Seeds",
    price: "₹1,200",
    description: "High-yield certified wheat seeds, drought-resistant variety with 95% germination rate.",
    emoji: "🌾",
    badge: "Best Seller",
    badgeColor: "bg-amber-500",
    shopifyUrl: `${STORE}/collections/seeds`,
  },
  {
    id: 2,
    name: "NPK Fertilizer 50kg",
    price: "₹2,800",
    description: "Balanced 20-20-20 NPK blend for optimal crop nutrition and maximum yield boost.",
    emoji: "🧪",
    badge: "Popular",
    badgeColor: "bg-blue-500",
    shopifyUrl: `${STORE}/collections/fertilizers`,
  },
  {
    id: 3,
    name: "Drip Irrigation Kit",
    price: "₹8,500",
    description: "Complete drip system for 1 acre, saves 60% water. Includes pipes, emitters & timer.",
    emoji: "💧",
    badge: "New",
    badgeColor: "bg-cyan-500",
    shopifyUrl: `${STORE}/collections/irrigation`,
  },
  {
    id: 4,
    name: "Garden Sprayer 16L",
    price: "₹3,200",
    description: "Professional backpack sprayer with anti-drip nozzle, ergonomic straps and pressure gauge.",
    emoji: "🔫",
    badge: "Hot Deal",
    badgeColor: "bg-red-500",
    shopifyUrl: `${STORE}/collections/tools`,
  },
  {
    id: 5,
    name: "Organic Compost 25kg",
    price: "₹950",
    description: "100% natural composted manure, enriches soil structure and promotes healthy root growth.",
    emoji: "♻️",
    badge: "Organic",
    badgeColor: "bg-green-600",
    shopifyUrl: `${STORE}/collections/organic`,
  },
  {
    id: 6,
    name: "Soil Testing Kit",
    price: "₹1,750",
    description: "Digital pH + NPK soil tester, 100 tests included. Know your soil, grow better crops.",
    emoji: "🧫",
    badge: "Essential",
    badgeColor: "bg-purple-500",
    shopifyUrl: `${STORE}/collections/tools`,
  },
];

export const features = [
  {
    icon: "🌱",
    title: "Quality Seeds",
    description: "Certified, high-yield seeds sourced from top agricultural labs. Backed by 95%+ germination guarantee.",
  },
  {
    icon: "🌿",
    title: "Organic Fertilizers",
    description: "100% natural, chemical-free fertilizers that enrich soil health while boosting crop yield sustainably.",
  },
  {
    icon: "👨‍🌾",
    title: "Expert Support",
    description: "Our agri-experts are available 24/7 to guide you on crop management, pest control, and soil health.",
  },
];